-
 name: this will install package based on operating system you are providing instruction
 hosts: servers
 become: yes
 tasks:
   - name: install Docker
     apt:
       name: docker.io
       state: latest
   - name: install aws cli
     apt:
       name: awscli
       state: latest
     when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
